### ISSUE TITLE
image server is down

### ISSUE THREAD

**Issue by yceballost** [manasky/lorem.space#8]
![image](https://user-images.githubusercontent.com/6722153/219399393-910e0e99-5fba-47ae-b479-a250ffca5d08.png)

**Comment by saadeghi** [comment]
It is fixed now. But the website is not being maintained anymore. Server costs are more than the ad profits and no one ever made a donation so with this circumstances I wouldn't expect it to stay alive much longer.   
You might want to run the script on your own server. It's open source anyway.
